
# Netlify configuration file
[build]
  publish = "dist"
  command = "npm run build"

# Handle SPA routing by redirecting all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
